### ISSUE TITLE
possibility to use redux devtools?

### ISSUE THREAD

**Issue by isc30** [lostpebble/pullstate#124]
Hi, this lib is amazing! Is it possible to use redux devtools to debug?

**Comment by lostpebble** [comment]
Hi @isc30 , thanks for the kind words! :)

Actually, redux devtools has always worked- I just forgot to put anything in the docs about it... Here is the link to the relevant info, which I've added today: https://lostpebble.github.io/pullstate/docs/redux-dev-tools
