### ISSUE TITLE
How to Reset all the stores?

### ISSUE THREAD

**Issue by SteJ13** [lostpebble/pullstate#159]
### Discussed in https://github.com/lostpebble/pullstate/discussions/158

<div type='discussions-op-text'>

<sup>Originally posted by **SteJ13** September 29, 2022</sup>
I am new to pullstate and I liked it very much. It is very useful and best alternate for redux. Thanks to the community.

Since I am new to this package I don't know how to reset all the stores. Eg. I have around 5 files with 5 seperate stores. When I logout the user and login as a new user the old data is still in the store which I don't need them. I know I can update the initial state but for many stores it may be difficult. Can any one of you guide me to overcome this issue?</div>

**Comment by lostpebble** [comment]
Hi,

I would recommend creating a function called `getDefaultStoreState()` or something along those lines.

You can use this function to fill the store when you initialize it for the first time. And then you can also call `Store.replace(getDefaultStoreState())` when you need it to be reset. Stores are individually managed and not connected in any way, so you'd have to do this for each store.

Store state management is entirely up to you, and there are multiple ways to deal with these kinds of issues.

In the future it might make sense for a `Store.reset()` method.

Hope that helps you!
