### ISSUE TITLE
Is 'pullstate' library still actively maintained?

### ISSUE THREAD

**Issue by andreifloricel** [lostpebble/pullstate#170]
Hi @lostpebble ,
I'm looking for a state management library for a medium/large React app I'm building from scratch and I'm currently struggling between 'pullstate' and `Zustand'.
My first choice would be 'pullstate' (btw, congrats on this library: it's unbelievably powerful and yet so simple to understand).

I'm only hesitating because it's not clear to me if this library is still active.
Do you plan to continue maintaining it?
Also, what is the compatibility with React 18 and the latest features regarding SSR/SSC etc.?
Thanks

**Comment by lostpebble** [comment]
Hi @andreifloricel ,

The library is pretty "feature complete" at the moment, so not much extra work is being done on it. But it is definitely not dead, and is being actively maintained. I used it in a lot of large projects still.

> Also, what is the compatibility with React 18 and the latest features regarding SSR/SSC etc.?

I haven't done loads of testing with the new SSC stuff, but it is compatible with React 18 so far.

**Comment by andreifloricel** [comment]
Thanks!
I noticed that there are some issues related to incomplete/outdated documentation.
Let me know if I can help in any way.
