### ISSUE TITLE
Any way to cancel actions? or to restrict concurrent fetches?

### ISSUE THREAD

**Issue by ggat** [lostpebble/pullstate#171]
Is there a way to implement behavior such as takeLatest in Redux-Saga and switchMap in RxJS?

Where, when an action is run a check is made to see if the same action is already running and if yes the previous call is cancelled before starting the new one.

![action_cancellation](https://github.com/lostpebble/pullstate/assets/14810832/8530c651-778b-4500-bdf5-b35c776fb658)

**Comment by lostpebble** [comment]
Hi,

Admittedly this is not well documented, but you can achieve this by forcing the "cache" to break when you next run the async action.

That's an option you can pass when doing `action.use({ cacheBreak: true })` or `action.run({ respectCache: false })`. This should force the action to run again, ignoring the currently running action, and the old action should have no post-action effects anymore.

Sorry for the late response, meant to get to this but it got lost in the bustle.
