### ISSUE TITLE
Dynamic getSubState in useStoreState

### ISSUE THREAD

**Issue by richardvuu** [lostpebble/pullstate#22]
I have a case where I want to get a list of data based on some prop.

```
const myComponent = ({type}) => {
  let data = useStoreState(store, (s) => s[type]);
  // do stuff with data
}
```

However, the selector is not updating when I change the `type` prop. Is there any way to make this work?

**Comment by lostpebble** [comment]
Hi there,

That's a good use-case which I surprisingly have never had to use yet. I've added that in to the next version now. You can grab it at `1.9.0`

You can now pass in a third argument, an array of dependencies similar to how `useEffect()` and such work, which will cause the listener to use the new passed function:

```js
const myComponent = ({type}) => {
  let data = useStoreState(store, (s) => s[type], [type]);
  // do stuff with data
}
```

Thanks for bringing my attention to a useful use-case!
