### ISSUE TITLE
Update fast-deep-equal, consider es6 variant

### ISSUE THREAD

**Issue by richardvuu** [lostpebble/pullstate#24]
The package is using `fast-deep-equal@2.0.1`, and this dependency has been updated to include support for es6 structs like Map/Set.

With fast-deep-equal@3.1.1 and importing as `const isEqual = require("fast-deep-equal/es6");` allows using Map objects inside the store. Without it, the store doesn't detect any changes.

But perhaps that breaks for older Node versions?

(btw, thanks for the prior fix 👍)

**Comment by lostpebble** [comment]
Hi again,

Cool, I updated to that version and it should all be working now with Maps and Sets. You can use pullstate `1.10.0` to see the new changes.

**Comment by richardvuu** [comment]
Extra! 👍
