### ISSUE TITLE
Mixed CJS require and ES imports causing issues

### ISSUE THREAD

**Issue by intrnl** [lostpebble/pullstate#29]
I've been using this library for a while now, it seems really nice! :+1: 

However, there's this one thing I noticed when trying to get this to work on a web app built with Rollup (previous project was with Webpack)

Mixed usage of CommonJS require and ES imports seems to be causing a havoc when trying to consume the library, Immer does not seem to be imported into the bundle at all, the require call is kept intact.

This is from what I can assume by looking at the bundled code and messing around with Pullstate itself, if this issue actually comes from somewhere else like in my Rollup configuration, please let me know! :smile:

**Comment by lostpebble** [comment]
Hi there,

Okay I see what you're saying. It could be that ways I was using `require("immer")` was breaking this for you.

I've updated the project to import them correctly (with much fuss being kicked up from Typescript 😬 ) - so should be okay now.

Let me know if that solves your issues.

**Comment by intrnl** [comment]
That seems to have fixed it! Thank you! :smile:
