### ISSUE TITLE
run() with respectCache returns null if running twice

### ISSUE THREAD

**Issue by schummar** [lostpebble/pullstate#40]
If I execute run() with `{ respectCache: true }` and the same key twice - the second instance before the first finishes - the second instance returns null immediately. It's easy to see why and I would be glad to offer a PR to solve it, but I'm not 100% certain what the intended behavior would even be. ;-) So let's clarify:

Most cases are pretty clear:
1. run() without respectCache => run individually, easy
2. run() with respectCache, but there is already something actually cached (no matter whether another call runs, it makes sense to return cache right away, since we stated we don't need most up-to-date data) =>return the cached value, again easy
3. run() with respectCache, while another instance is running (either because cache was empty to begin with or it was executed without `respectCache`) => Now it gets interesting. I personally would consider the cache still empty at this point (but pullstate currently treats it as a cached error state). Now we could start another instance or - my preference - wait for the already running instance to finish and use its result.

I don't know how exactly this api was intended, so your understanding might differ. In case you agree I can make a PR.

**Comment by lostpebble** [comment]
Your understanding is exactly correct as to how the API was intended.

For point 3, it should detect that there is currently an action running, and wait for the result of that - and return that result from `run()`.

Thanks for the issue. I'll take a quick look as to why its not working as intended. Could be that I missed one of the checks on the `clientAsyncCache.actions`, which keeps track of the currently running promises per an action, when I did some recently refactoring. (or it was never implemented properly in the first place...)

**Comment by lostpebble** [comment]
Released in `v1.13.1` . Much thanks @schummar ! :)
