### ISSUE TITLE
Accessing a store without a hook?

### ISSUE THREAD

**Issue by jakcharlton** [lostpebble/pullstate#46]
I have a function that does some updating, but I want it to be able to read the state at the beginning before it decides what to change

The function is outside a React component, so no hook option ... can the state be directly accessed any other way?  (was using hookstate for a while, where the hook is just a thin wrapper)

**Comment by lostpebble** [comment]
Hi @jakcharlton ,

Yes, if you need to direct state of a store at any given moment, you can use `Store.getRawState()`.

You could also just run an update as per usual - and look at the second argument in the update function, which is the current raw read-only state. And update doesn't _have_ to update anything, and you can run conditionals inside it if you like.

**Comment by jakcharlton** [comment]
@lostpebble that's awesome thanks. Love the simplicity of the API to pullstate.

**Comment by lostpebble** [comment]
Thanks, glad you're enjoying it :)
