### ISSUE TITLE
Update store outside of immer?

### ISSUE THREAD

**Issue by mlynch** [lostpebble/pullstate#73]
I have a unique use case where I'm updating a deep tree (imagine a DOM-like representation). For this field in my store, it's a nightmare to update and patch it using immer.

Is it possible to update the store directly without using `update` and the `Proxy` system immer uses?

I would probably then update a flag in the store that would be essentially a mock for this field to trigger re-rendering.

**Comment by lostpebble** [comment]
Hi @mlynch ,

I guess if it was necessary to do something like this, you could get away with:

```ts
const state = MyStore.getRawState();

// Copy and do your changes

MyStore.replace(newState);
```

If your changes are synchronous, I think it should be okay.

`replace()` will run an update on your store, so no need to put in mock fields for re-rendering.

If there is a nicer API directly on the store for times like these you can think of, I'll try and add it- as I have run into similar annoyances with deep structures and immer updates.

**Comment by mlynch** [comment]
Thanks for the tip! I tried this and one thing I'm running into is the state object comes back as read-only, so I can't mutate it. I'd like to avoid copying the whole tree though I suppose that's an option and wouldn't be a huge deal:

<img width="967" alt="Screen Shot 2020-11-10 at 9 10 58 PM" src="https://user-images.githubusercontent.com/11214/98760653-59e3c580-2399-11eb-8c5f-84439cdec613.png">

**Comment by lostpebble** [comment]
I think this might have something to do with immer "freezing" data structures which are returned from a producer.

Check this out: https://immerjs.github.io/immer/docs/freezing

I think in general it is just a development failsafe to expose unintended mutations- so in production your data structures should actually be mutable outside of the store (failsafe removed for performance reasons, I assume). To get the same behaviour in dev, you apparently need to run `setAutoFreeze(false)`, imported from `immer` .

Check if this works, otherwise yea- storing these kinds of large structures outside of the store isn't a bad idea, and updating a store with `replace()` with each new change, just takes a bit more care.

**Comment by lostpebble** [comment]
Hi @mlynch ,

If you ran into any more issues with this let me know. If you think there's a way this could be better managed with Pullstate itself, feel free to say so too.

Otherwise, gonna close this for now as it seems like its been resolved.

**Comment by mlynch** [comment]
Sorry, never followed up! Really appreciate the help. Haven't had a chance to try this but will and let you know how it works for me.

**Comment by mlynch** [comment]
It's been a long time but I remembered this issue and just want to say I revisited this for something else I've been working on and the solution worked really well. Disabling freezing and using replace has made some of these nightmarish immer updates much more reasonable and probably way more performant without all the copying and immutable array/object creation. I think this is a necessary and useful escape hatch for these situations. Thanks for the help.

**Comment by lostpebble** [comment]
No worries, glad its working out well!

I actually recently added a new method called `Store.replaceFromCurrent()`, which solves this issue a little cleaner. It takes a function, which will have the current state as its argument and should return a new state. Stops you from having to use `Store.getRawState()` in these situations.

**Comment by mlynch** [comment]
Oh nice! Will give that a try. Thanks @lostpebble
