### ISSUE TITLE
[Question] How to pass arguments to multiple updaters?

### ISSUE THREAD

**Issue by LinusJohannsen** [lostpebble/pullstate#94]
Hey, in the [Docs](https://lostpebble.github.io/pullstate/docs/update-store#example-with-multiple-updaters) you pass in an array of multiple updaters like:

`CountStore.update([incrementCount, decrementCount]);`

I have a function:
`const incrementCount = (s) => {
  s.count += 1
}`

and i want to use an additional parameter 'value': 
`const incrementCount = (s, value) => {
  s.count += value
}`

How do i pass the value as an argument in the array?

Writing `CountStore.update([incrementCount(20), decrementCount]);` does not work. What am i doing wrong?

Thanks!

**Comment by lostpebble** [comment]
Hi @LinusJohannsen ,

So in this case you'd have to create a wrapped updater. If you ever want to create an updater function that takes arguments, it needs to be wrapped.

So you could do something like this:

```ts
const incrementCount = (value) => (s) => { s.count += value };
```

In this specific situation, I'd probably just make a single function if all these functions were doing is altering the count:

```ts
const affectCount = (amount) => (s) => { s.count += amount };

CountStore.update([affectCount(20), affectCount(-1)]); // redundant - but just for the sake of example.
```

So yea, basically what the functions are actually doing is provisioning a plain updater function with the specific arguments needed for that update and returning a new plain updater function, which is then used by the store to update.

I tend to use different naming conventions for updaters which are wrapped and those which are not, something like `affectCount_with` - the `with` to indicate that we are doing the action _with_ some kind of input value.

```ts
CountStore.update([affectCount_with(20), decrementCount]);
```

Hope that helps!
